M48
; DRILL file {KiCad 9.0.6} date 2026-03-19T13:41:58-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-19T13:41:58-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X76.43Y-92.938
X84.43Y-92.938
T2
X26.7Y-24.825
X26.7Y-87.575
X100.1Y-87.675
X100.2Y-24.825
M30
