M48
; DRILL file {KiCad 9.0.6} date 2026-03-14T06:17:14-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-14T06:17:14-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X120.85Y-128.463
X128.85Y-128.463
T2
X71.15Y-60.35
X71.15Y-123.1
X144.55Y-123.2
X144.65Y-60.35
M30
