board: FigCNC
name: FigCNC Standard Single Y-AXIS
stepping:
  engine: RMT
  idle_ms: 250
  pulse_us: 10
  dir_delay_us: 6
  disable_delay_us: 0

axes:
  shared_stepper_disable_pin: NO_PIN
  x:
    steps_per_mm: 320.000
    max_rate_mm_per_min: 2500.000
    acceleration_mm_per_sec2: 100.000
    max_travel_mm: 327
    soft_limits: true
    homing:
      cycle: 1
      positive_direction: true
      mpos_mm: 1.000
      feed_mm_per_min: 300.000
      seek_mm_per_min: 600.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: gpio.32
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 1.000
      stepstick:
        ms3_pin: NO_PIN
        step_pin: gpio.22
        direction_pin: gpio.13
        disable_pin: NO_PIN

  y:
    steps_per_mm: 400.000
    max_rate_mm_per_min: 3000.000
    acceleration_mm_per_sec2: 100.000
    max_travel_mm: 327.000
    soft_limits: true
    homing:
      cycle: 1
      positive_direction: true
      mpos_mm: 0.000
      feed_mm_per_min: 300.000
      seek_mm_per_min: 600.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: gpio.35
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 1
      stepstick:
        ms3_pin: NO_PIN
        step_pin: gpio.14
        direction_pin: gpio.27
        disable_pin: NO_PIN

  z:
    steps_per_mm: 320.000
    max_rate_mm_per_min: 1600.000
    acceleration_mm_per_sec2: 100.000
    max_travel_mm: 95.000
    soft_limits: true
    homing:
      cycle: 1
      positive_direction: true
      mpos_mm: 0.000
      feed_mm_per_min: 300.000
      seek_mm_per_min: 600.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: gpio.39
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 1.000
      stepstick:
        ms3_pin: NO_PIN
        step_pin: gpio.25
        direction_pin: gpio.33
        disable_pin: NO_PIN


control:
  safety_door_pin: NO_PIN
  reset_pin: NO_PIN
  feed_hold_pin: NO_PIN
  cycle_start_pin: NO_PIN

spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18


sdcard:
  cs_pin: gpio.5
  card_detect_pin: NO_PIN
  frequency_hz: 4000000

probe:
  pin: gpio.36:low
  check_mode_start: false


uart1:
  txd_pin: gpio.1
  rxd_pin: gpio.3
  rts_pin: NO_PIN
  cts_pin: NO_PIN
  baud: 1000000
  mode: 8N1

uart_channel1:
  uart_num: 1
  report_interval_ms: 75

# Pendant
uart2:
  txd_pin: gpio.17
  rxd_pin: gpio.16
  rts_pin: NO_PIN
  cts_pin: NO_PIN
  baud: 1000000
  mode: 8N1

uart_channel2:
  uart_num: 2
  report_interval_ms: 75

start:
  must_home: false
